# Generated by Django 4.2.7 on 2023-11-21 23:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(max_length=11)),
                ('RG', models.CharField(max_length=9)),
                ('foto', models.ImageField(upload_to='')),
                ('is_condutor', models.BooleanField(default=False)),
                ('is_passageiro', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_partida', models.CharField(max_length=100)),
                ('local_chegada', models.CharField(max_length=100)),
                ('horario_partida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('lugares', models.IntegerField()),
                ('placa_veiculo', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('ativa', models.BooleanField()),
                ('vagas', models.IntegerField()),
                ('carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.carona')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_media', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passageiros_corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.corrida')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passageiro')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('hora', models.DateTimeField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.corrida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_media', models.FloatField()),
                ('CNH', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carona',
            name='condutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.condutor'),
        ),
        migrations.CreateModel(
            name='Avaliacao_Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passageiro')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.condutor')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.corrida')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao_Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.condutor')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.passageiro')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.corrida')),
            ],
        ),
    ]
