# Generated by Django 4.2.7 on 2023-11-22 00:13

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', accounts.models.UsuarioManager()),
            ],
        ),
    ]
