# Generated by Django 4.2.7 on 2023-11-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condutor',
            name='CNH',
            field=models.CharField(max_length=11),
        ),
    ]
