# Generated by Django 4.2.7 on 2023-11-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passageiros_corrida_aceito'),
        ('accounts', '0005_alter_usuario_foto'),
    ]

    operations = [
    ]
