# Generated by Django 4.2.7 on 2023-11-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20231126_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='endereco_chegada',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carona',
            name='endereco_partida',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carona',
            name='placeId_chegada',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carona',
            name='placeId_partida',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carona',
            name='local_chegada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carona',
            name='local_partida',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='nota_media',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(default=False)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.corrida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
