# Generated by Django 4.2.6 on 2023-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_carona_endereco_chegada_carona_endereco_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condutor',
            name='nota_media',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
