# Generated by Django 4.2.6 on 2023-11-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notificacao_para_condutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='corrida',
        ),
    ]
